// Do not edit. This file is machine generated by the Resource DLL Wizard.

library DrvSM;

{$R *.RES}
{ITE} {DFMFileType} {UNITS\About.dfm}
{ITE} {DFMFileType} {UNITS\Connect.dfm}
{ITE} {DFMFileType} {UNITS\EditLD.dfm}
{ITE} {DFMFileType} {UNITS\showresfind.dfm}
{ITE} {DFMFileType} {UNITS\Unit1.dfm}
{ITE} {RCFileType} {DrvSM_DRC.rc}

{$R 'UNITS\About.dfm' frmAbout:TForm}
{$R 'UNITS\Connect.dfm' frmConnect:TPropertyPage}
{$R 'UNITS\EditLD.dfm' frmLD:TForm}
{$R 'UNITS\showresfind.dfm' frmFindDevice:TForm}
{$R 'UNITS\Unit1.dfm' Form1:TForm}
{$R 'DrvSM_DRC.res' 'DrvSM_DRC.rc'}

{$E RUS}

begin
end.